export const STUDIES = 'STUDIES';
export const STUDIES_SUCCESS = 'STUDIES_SUCCESS';
export const STUDIES_ERROR = 'STUDIES_ERROR';
export const STUDIES__CLEAR = 'STUDIES__CLEAR';

export const SERIES_GET = 'SERIES_GET';
export const SERIES_GET_SUCCESS = 'SERIES_GET_SUCCESS';
export const SERIES_GET_ERROR = 'SERIES_GET_ERROR';
export const SERIES_GET__CLEAR = 'SERIES_GET__CLEAR';

export const SERIES_DETAILS_GET = 'SERIES_DETAILS_GET';
export const SERIES_DETAILS_GET_SUCCESS = 'SERIES_DETAILS_GET_SUCCESS';
export const SERIES_DETAILS_GET_ERROR = 'SERIES_DETAILS_GET_ERROR';

export const INSTANCE_ID_GET = 'INSTANCE_ID_GET';
export const INSTANCE_ID_GET_SUCCESS = 'INSTANCE_ID_GET_SUCCESS';
export const INSTANCE_ID_GET_ERROR = 'INSTANCE_ID_GET_ERROR';

export const INSTANCE_GET = 'INSTANCE_GET';
export const INSTANCE_GET_SUCCESS = 'INSTANCE_GET_SUCCESS';
export const INSTANCE_GET_ERROR = 'INSTANCE_GET_ERROR';