/*
  ~  Copyright 2016 Ripple Foundation C.I.C. Ltd
  ~  
  ~  Licensed under the Apache License, Version 2.0 (the "License");
  ~  you may not use this file except in compliance with the License.
  ~  You may obtain a copy of the License at
  ~  
  ~    http://www.apache.org/licenses/LICENSE-2.0

  ~  Unless required by applicable law or agreed to in writing, software
  ~  distributed under the License is distributed on an "AS IS" BASIS,
  ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  See the License for the specific language governing permissions and
  ~  limitations under the License.
*/
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const PATIENTS = 'PATIENTS';
export const PATIENTS_SUCCESS = 'PATIENTS_SUCCESS';
export const PATIENTS_ERROR = 'PATIENTS_ERROR';

export const PATIENTS_GET = 'PATIENTS_GET';
export const PATIENTS_GET_SUCCESS = 'PATIENTS_GET_SUCCESS';
export const PATIENTS_GET_ERROR = 'PATIENTS_GET_ERROR';

export const DIAGNOSES = 'DIAGNOSES';
export const DIAGNOSES_SUCCESS = 'DIAGNOSES_SUCCESS';
export const DIAGNOSES_ERROR = 'DIAGNOSES_ERROR';

export const DIAGNOSES_GET = 'DIAGNOSES_GET';
export const DIAGNOSES_GET_SUCCESS = 'DIAGNOSES_GET_SUCCESS';
export const DIAGNOSES_GET_ERROR = 'DIAGNOSES_GET_ERROR';

export const DIAGNOSES_CREATE = 'DIAGNOSES_CREATE';
export const DIAGNOSES_CREATE_SUCCESS = 'DIAGNOSES_CREATE_SUCCESS';
export const DIAGNOSES_CREATE_ERROR = 'DIAGNOSES_CREATE_ERROR';

export const DIAGNOSES_UPDATE = 'DIAGNOSES_UPDATE';
export const DIAGNOSES_UPDATE_SUCCESS = 'DIAGNOSES_UPDATE_SUCCESS';
export const DIAGNOSES_UPDATE_ERROR = 'DIAGNOSES_UPDATE_ERROR';

export const ALLERGIES = 'ALLERGIES';
export const ALLERGIES_SUCCESS = 'ALLERGIES_SUCCESS';
export const ALLERGIES_ERROR = 'ALLERGIES_ERROR';

export const ALLERGIES_GET = 'ALLERGIES_GET';
export const ALLERGIES_GET_SUCCESS = 'ALLERGIES_GET_SUCCESS';
export const ALLERGIES_GET_ERROR = 'ALLERGIES_GET_ERROR';

export const ALLERGIES_CREATE = 'ALLERGIES_CREATE';
export const ALLERGIES_CREATE_SUCCESS = 'ALLERGIES_CREATE_SUCCESS';
export const ALLERGIES_CREATE_ERROR = 'ALLERGIES_CREATE_ERROR';

export const ALLERGIES_UPDATE = 'ALLERGIES_UPDATE';
export const ALLERGIES_UPDATE_SUCCESS = 'ALLERGIES_UPDATE_SUCCESS';
export const ALLERGIES_UPDATE_ERROR = 'ALLERGIES_UPDATE_ERROR';

export const MEDICATIONS = 'MEDICATIONS';
export const MEDICATIONS_SUCCESS = 'MEDICATIONS_SUCCESS';
export const MEDICATIONS_ERROR = 'MEDICATIONS_ERROR';

export const MEDICATIONS_GET = 'MEDICATIONS_GET';
export const MEDICATIONS_GET_SUCCESS = 'MEDICATIONS_GET_SUCCESS';
export const MEDICATIONS_GET_ERROR = 'MEDICATIONS_GET_ERROR';

export const MEDICATIONS_CREATE = 'MEDICATIONS_CREATE';
export const MEDICATIONS_CREATE_SUCCESS = 'MEDICATIONS_CREATE_SUCCESS';
export const MEDICATIONS_CREATE_ERROR = 'MEDICATIONS_CREATE_ERROR';

export const MEDICATIONS_UPDATE = 'MEDICATIONS_UPDATE';
export const MEDICATIONS_UPDATE_SUCCESS = 'MEDICATIONS_UPDATE_SUCCESS';
export const MEDICATIONS_UPDATE_ERROR = 'MEDICATIONS_UPDATE_ERROR';

export const CONTACTS = 'CONTACTS';
export const CONTACTS_SUCCESS = 'CONTACTS_SUCCESS';
export const CONTACTS_ERROR = 'CONTACTS_ERROR';

export const CONTACTS_GET = 'CONTACTS_GET';
export const CONTACTS_GET_SUCCESS = 'CONTACTS_GET_SUCCESS';
export const CONTACTS_GET_ERROR = 'CONTACTS_GET_ERROR';

export const CONTACTS_CREATE = 'CONTACTS_CREATE';
export const CONTACTS_CREATE_SUCCESS = 'CONTACTS_CREATE_SUCCESS';
export const CONTACTS_CREATE_ERROR = 'CONTACTS_CREATE_ERROR';

export const CONTACTS_UPDATE = 'CONTACTS_UPDATE';
export const CONTACTS_UPDATE_SUCCESS = 'CONTACTS_UPDATE_SUCCESS';
export const CONTACTS_UPDATE_ERROR = 'CONTACTS_UPDATE_ERROR';

export const ORDERS = 'ORDERS';
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_ERROR = 'ORDERS_ERROR';

export const ORDERS_GET = 'ORDERS_GET';
export const ORDERS_GET_SUCCESS = 'ORDERS_GET_SUCCESS';
export const ORDERS_GET_ERROR = 'ORDERS_GET_ERROR';

export const ORDERS_CREATE = 'ORDERS_CREATE';
export const ORDERS_CREATE_SUCCESS = 'ORDERS_CREATE_SUCCESS';
export const ORDERS_CREATE_ERROR = 'ORDERS_CREATE_ERROR';

export const ORDERS_SUGGESTION = 'ORDERS_SUGGESTION';
export const ORDERS_SUGGESTION_SUCCESS = 'ORDERS_SUGGESTION_SUCCESS';
export const ORDERS_SUGGESTION_ERROR = 'ORDERS_SUGGESTION_ERROR';

export const REFERRALS = 'REFERRALS';
export const REFERRALS_SUCCESS = 'REFERRALS_SUCCESS';
export const REFERRALS_ERROR = 'REFERRALS_ERROR';

export const REFERRALS_GET = 'REFERRALS_GET';
export const REFERRALS_GET_SUCCESS = 'REFERRALS_GET_SUCCESS';
export const REFERRALS_GET_ERROR = 'REFERRALS_GET_ERROR';

export const REFERRALS_CREATE = 'REFERRALS_CREATE';
export const REFERRALS_CREATE_SUCCESS = 'REFERRALS_CREATE_SUCCESS';
export const REFERRALS_CREATE_ERROR = 'REFERRALS_CREATE_ERROR';

export const REFERRALS_UPDATE = 'REFERRALS_UPDATE';
export const REFERRALS_UPDATE_SUCCESS = 'REFERRALS_UPDATE_SUCCESS';
export const REFERRALS_UPDATE_ERROR = 'REFERRALS_UPDATE_ERROR';

export const PROCEDURES = 'PROCEDURES';
export const PROCEDURES_SUCCESS = 'PROCEDURES_SUCCESS';
export const PROCEDURES_ERROR = 'PROCEDURES_ERROR';

export const PROCEDURES_GET = 'PROCEDURES_GET';
export const PROCEDURES_GET_SUCCESS = 'PROCEDURES_GET_SUCCESS';
export const PROCEDURES_GET_ERROR = 'PROCEDURES_GET_ERROR';

export const PROCEDURES_CREATE = 'PROCEDURES_CREATE';
export const PROCEDURES_CREATE_SUCCESS = 'PROCEDURES_CREATE_SUCCESS';
export const PROCEDURES_CREATE_ERROR = 'PROCEDURES_CREATE_ERROR';

export const PROCEDURES_UPDATE = 'PROCEDURES_UPDATE';
export const PROCEDURES_UPDATE_SUCCESS = 'PROCEDURES_UPDATE_SUCCESS';
export const PROCEDURES_UPDATE_ERROR = 'PROCEDURES_UPDATE_ERROR';

export const DOCUMENTS = 'DOCUMENTS';
export const DOCUMENTS_SUCCESS = 'DOCUMENTS_SUCCESS';
export const DOCUMENTS_ERROR = 'DOCUMENTS_ERROR';

export const DOCUMENTS_FIND_REFERRAL = 'DOCUMENTS_FIND_REFERRAL';
export const DOCUMENTS_FIND_REFERRAL_SUCCESS = 'DOCUMENTS_FIND_REFERRAL_SUCCESS';
export const DOCUMENTS_FIND_REFERRAL_ERROR = 'DOCUMENTS_FIND_REFERRAL_ERROR';

export const DOCUMENTS_UPLOAD_REFERRAL = 'DOCUMENTS_UPLOAD_REFERRAL';
export const DOCUMENTS_UPLOAD_REFERRAL_SUCCESS = 'DOCUMENTS_UPLOAD_REFERRAL_SUCCESS';
export const DOCUMENTS_UPLOAD_REFERRAL_ERROR = 'DOCUMENTS_UPLOAD_REFERRAL_ERROR';

export const DOCUMENTS_FIND_DISCHARGE = 'DOCUMENTS_FIND_DISCHARGE';
export const DOCUMENTS_FIND_DISCHARGE_SUCCESS = 'DOCUMENTS_FIND_DISCHARGE_SUCCESS';
export const DOCUMENTS_FIND_DISCHARGE_ERROR = 'DOCUMENTS_FIND_DISCHARGE_ERROR';

export const DOCUMENTS_UPLOAD_DISCHARGE = 'DOCUMENTS_UPLOAD_DISCHARGE';
export const DOCUMENTS_UPLOAD_DISCHARGE_SUCCESS = 'DOCUMENTS_UPLOAD_DISCHARGE_SUCCESS';
export const DOCUMENTS_UPLOAD_DISCHARGE_ERROR = 'DOCUMENTS_UPLOAD_DISCHARGE_ERROR';

export const APPOINTMENTS = 'APPOINTMENTS';
export const APPOINTMENTS_SUCCESS = 'APPOINTMENTS_SUCCESS';
export const APPOINTMENTS_ERROR = 'APPOINTMENTS_ERROR';

export const APPOINTMENTS_GET = 'APPOINTMENTS_GET';
export const APPOINTMENTS_GET_SUCCESS = 'APPOINTMENTS_GET_SUCCESS';
export const APPOINTMENTS_GET_ERROR = 'APPOINTMENTS_GET_ERROR';

export const APPOINTMENTS_CREATE = 'APPOINTMENTS_CREATE';
export const APPOINTMENTS_CREATE_SUCCESS = 'APPOINTMENTS_CREATE_SUCCESS';
export const APPOINTMENTS_CREATE_ERROR = 'APPOINTMENTS_CREATE_ERROR';

export const APPOINTMENTS_UPDATE = 'APPOINTMENTS_UPDATE';
export const APPOINTMENTS_UPDATE_SUCCESS = 'APPOINTMENTS_UPDATE_SUCCESS';
export const APPOINTMENTS_UPDATE_ERROR = 'APPOINTMENTS_UPDATE_ERROR';

export const EOLCAREPLANS = 'EOLCAREPLANS';
export const EOLCAREPLANS_SUCCESS = 'EOLCAREPLANS_SUCCESS';
export const EOLCAREPLANS_ERROR = 'EOLCAREPLANS_ERROR';

export const EOLCAREPLANS_GET = 'EOLCAREPLANS_GET';
export const EOLCAREPLANS_GET_SUCCESS = 'EOLCAREPLANS_GET_SUCCESS';
export const EOLCAREPLANS_GET_ERROR = 'EOLCAREPLANS_GET_ERROR';

export const EOLCAREPLANS_CREATE = 'EOLCAREPLANS_CREATE';
export const EOLCAREPLANS_CREATE_SUCCESS = 'EOLCAREPLANS_CREATE_SUCCESS';
export const EOLCAREPLANS_CREATE_ERROR = 'EOLCAREPLANS_CREATE_ERROR';

export const EOLCAREPLANS_UPDATE = 'EOLCAREPLANS_UPDATE';
export const EOLCAREPLANS_UPDATE_SUCCESS = 'EOLCAREPLANS_UPDATE_SUCCESS';
export const EOLCAREPLANS_UPDATE_ERROR = 'EOLCAREPLANS_UPDATE_ERROR';

export const RESULTS = 'RESULTS';
export const RESULTS_SUCCESS = 'RESULTS_SUCCESS';
export const RESULTS_ERROR = 'RESULTS_ERROR';

export const RESULTS_GET = 'RESULTS_GET';
export const RESULTS_GET_SUCCESS = 'RESULTS_GET_SUCCESS';
export const RESULTS_GET_ERROR = 'RESULTS_GET_ERROR';

export const SEARCH = 'SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';

export const CHART = 'CHART';
export const CHART_SUCCESS = 'CHART_SUCCESS';
export const CHART_ERROR = 'CHART_ERROR';

export const STUDIES = 'STUDIES';
export const STUDIES_SUCCESS = 'STUDIES_SUCCESS';
export const STUDIES_ERROR = 'STUDIES_ERROR';

export const SERIES_GET = 'SERIES_GET';
export const SERIES_GET_SUCCESS = 'SERIES_GET_SUCCESS';
export const SERIES_GET_ERROR = 'SERIES_GET_ERROR';

export const SERIES_DETAILS_GET = 'SERIES_DETAILS_GET';
export const SERIES_DETAILS_GET_SUCCESS = 'SERIES_DETAILS_GET_SUCCESS';
export const SERIES_DETAILS_GET_ERROR = 'SERIES_DETAILS_GET_ERROR';

export const INSTANCE_ID_GET = 'INSTANCE_ID_GET';
export const INSTANCE_ID_GET_SUCCESS = 'INSTANCE_ID_GET_SUCCESS';
export const INSTANCE_ID_GET_ERROR = 'INSTANCE_ID_GET_ERROR';

export const INSTANCE_GET = 'INSTANCE_GET';
export const INSTANCE_GET_SUCCESS = 'INSTANCE_GET_SUCCESS';
export const INSTANCE_GET_ERROR = 'INSTANCE_GET_ERROR';

export const GENERICMDT = 'GENERICMDT';
export const GENERICMDT_SUCCESS = 'GENERICMDT_SUCCESS';
export const GENERICMDT_ERROR = 'GENERICMDT_ERROR';

export const GENERICMDT_GET = 'GENERICMDT_GET';
export const GENERICMDT_GET_SUCCESS = 'GENERICMDT_GET_SUCCESS';
export const GENERICMDT_GET_ERROR = 'GENERICMDT_GET_ERROR';

export const GENERICMDT_CREATE = 'GENERICMDT_CREATE';
export const GENERICMDT_CREATE_SUCCESS = 'GENERICMDT_CREATE_SUCCESS';
export const GENERICMDT_CREATE_ERROR = 'GENERICMDT_CREATE_ERROR';

export const GENERICMDT_UPDATE = 'GENERICMDT_UPDATE';
export const GENERICMDT_UPDATE_SUCCESS = 'GENERICMDT_UPDATE_SUCCESS';
export const GENERICMDT_UPDATE_ERROR = 'GENERICMDT_UPDATE_ERROR';

export const CLINICALNOTES = 'CLINICALNOTES';
export const CLINICALNOTES_SUCCESS = 'CLINICALNOTES_SUCCESS';
export const CLINICALNOTES_ERROR = 'CLINICALNOTES_ERROR';

export const CLINICALNOTES_GET = 'CLINICALNOTES_GET';
export const CLINICALNOTES_GET_SUCCESS = 'CLINICALNOTES_GET_SUCCESS';
export const CLINICALNOTES_GET_ERROR = 'CLINICALNOTES_GET_ERROR';

export const CLINICALNOTES_CREATE = 'CLINICALNOTES_CREATE';
export const CLINICALNOTES_CREATE_SUCCESS = 'CLINICALNOTES_CREATE_SUCCESS';
export const CLINICALNOTES_CREATE_ERROR = 'CLINICALNOTES_CREATE_ERROR';

export const CLINICALNOTES_UPDATE = 'CLINICALNOTES_UPDATE';
export const CLINICALNOTES_UPDATE_SUCCESS = 'CLINICALNOTES_UPDATE_SUCCESS';
export const CLINICALNOTES_UPDATE_ERROR = 'CLINICALNOTES_UPDATE_ERROR';

export const TRANSFEROFCARE = 'TRANSFEROFCARE';
export const TRANSFEROFCARE_SUCCESS = 'TRANSFEROFCARE_SUCCESS';
export const TRANSFEROFCARE_ERROR = 'TRANSFEROFCARE_ERROR';

export const TRANSFEROFCARE_GET = 'TRANSFEROFCARE_GET';
export const TRANSFEROFCARE_GET_SUCCESS = 'TRANSFEROFCARE_GET_SUCCESS';
export const TRANSFEROFCARE_GET_ERROR = 'TRANSFEROFCARE_GET_ERROR';

export const TRANSFEROFCARE_CREATE = 'TRANSFEROFCARE_CREATE';
export const TRANSFEROFCARE_CREATE_SUCCESS = 'TRANSFEROFCARE_CREATE_SUCCESS';
export const TRANSFEROFCARE_CREATE_ERROR = 'TRANSFEROFCARE_CREATE_ERROR';

export const HEIGHTANDWEIGHT = 'HEIGHTANDWEIGHT';
export const HEIGHTANDWEIGHT_SUCCESS = 'HEIGHTANDWEIGHT_SUCCESS';
export const HEIGHTANDWEIGHT_ERROR = 'HEIGHTANDWEIGHT_ERROR';

export const HEIGHTANDWEIGHT_GET = 'HEIGHTANDWEIGHT_GET';
export const HEIGHTANDWEIGHT_GET_SUCCESS = 'HEIGHTANDWEIGHT_GET_SUCCESS';
export const HEIGHTANDWEIGHT_GET_ERROR = 'HEIGHTANDWEIGHT_GET_ERROR';

export const HEIGHTANDWEIGHT_CREATE = 'HEIGHTANDWEIGHT_CREATE';
export const HEIGHTANDWEIGHT_CREATE_SUCCESS = 'HEIGHTANDWEIGHT_CREATE_SUCCESS';
export const HEIGHTANDWEIGHT_CREATE_ERROR = 'HEIGHTANDWEIGHT_CREATE_ERROR';

export const HEIGHTANDWEIGHT_UPDATE = 'HEIGHTANDWEIGHT_UPDATE';
export const HEIGHTANDWEIGHT_UPDATE_SUCCESS = 'HEIGHTANDWEIGHT_UPDATE_SUCCESS';
export const HEIGHTANDWEIGHT_UPDATE_ERROR = 'HEIGHTANDWEIGHT_UPDATE_ERROR';