export const MEDICATIONS = 'MEDICATIONS';
export const MEDICATIONS_SUCCESS = 'MEDICATIONS_SUCCESS';
export const MEDICATIONS_ERROR = 'MEDICATIONS_ERROR';
export const MEDICATIONS__CLEAR = 'MEDICATIONS__CLEAR';

export const MEDICATIONS_GET = 'MEDICATIONS_GET';
export const MEDICATIONS_GET_SUCCESS = 'MEDICATIONS_GET_SUCCESS';
export const MEDICATIONS_GET_ERROR = 'MEDICATIONS_GET_ERROR';

export const MEDICATIONS_CREATE = 'MEDICATIONS_CREATE';
export const MEDICATIONS_CREATE_SUCCESS = 'MEDICATIONS_CREATE_SUCCESS';
export const MEDICATIONS_CREATE_ERROR = 'MEDICATIONS_CREATE_ERROR';

export const MEDICATIONS_UPDATE = 'MEDICATIONS_UPDATE';
export const MEDICATIONS_UPDATE_SUCCESS = 'MEDICATIONS_UPDATE_SUCCESS';
export const MEDICATIONS_UPDATE_ERROR = 'MEDICATIONS_UPDATE_ERROR';