export const TRANSFEROFCARE = 'TRANSFEROFCARE';
export const TRANSFEROFCARE_SUCCESS = 'TRANSFEROFCARE_SUCCESS';
export const TRANSFEROFCARE_ERROR = 'TRANSFEROFCARE_ERROR';
export const TRANSFEROFCARE__CLEAR = 'TRANSFEROFCARE__CLEAR';

export const TRANSFEROFCARE_GET = 'TRANSFEROFCARE_GET';
export const TRANSFEROFCARE_GET_SUCCESS = 'TRANSFEROFCARE_GET_SUCCESS';
export const TRANSFEROFCARE_GET_ERROR = 'TRANSFEROFCARE_GET_ERROR';

export const TRANSFEROFCARE_CREATE = 'TRANSFEROFCARE_CREATE';
export const TRANSFEROFCARE_CREATE_SUCCESS = 'TRANSFEROFCARE_CREATE_SUCCESS';
export const TRANSFEROFCARE_CREATE_ERROR = 'TRANSFEROFCARE_CREATE_ERROR';

export const TRANSFEROFCARE_UPDATE = 'TRANSFEROFCARE_UPDATE';
export const TRANSFEROFCARE_UPDATE_SUCCESS = 'TRANSFEROFCARE_UPDATE_SUCCESS';
export const TRANSFEROFCARE_UPDATE_ERROR = 'TRANSFEROFCARE_UPDATE_ERROR';