export const GENERICMDT = 'GENERICMDT';
export const GENERICMDT_SUCCESS = 'GENERICMDT_SUCCESS';
export const GENERICMDT_ERROR = 'GENERICMDT_ERROR';
export const GENERICMDT__CLEAR = 'GENERICMDT__CLEAR';

export const GENERICMDT_GET = 'GENERICMDT_GET';
export const GENERICMDT_GET_SUCCESS = 'GENERICMDT_GET_SUCCESS';
export const GENERICMDT_GET_ERROR = 'GENERICMDT_GET_ERROR';

export const GENERICMDT_CREATE = 'GENERICMDT_CREATE';
export const GENERICMDT_CREATE_SUCCESS = 'GENERICMDT_CREATE_SUCCESS';
export const GENERICMDT_CREATE_ERROR = 'GENERICMDT_CREATE_ERROR';

export const GENERICMDT_UPDATE = 'GENERICMDT_UPDATE';
export const GENERICMDT_UPDATE_SUCCESS = 'GENERICMDT_UPDATE_SUCCESS';
export const GENERICMDT_UPDATE_ERROR = 'GENERICMDT_UPDATE_ERROR';