export const PATIENTS = 'PATIENTS';
export const PATIENTS_SUCCESS = 'PATIENTS_SUCCESS';
export const PATIENTS_ERROR = 'PATIENTS_ERROR';

export const PATIENTS_GET = 'PATIENTS_GET';
export const PATIENTS_GET_SUCCESS = 'PATIENTS_GET_SUCCESS';
export const PATIENTS_GET_ERROR = 'PATIENTS_GET_ERROR';
export const PATIENTS_GET__CLEAR = 'PATIENTS_GET__CLEAR';