export const VACCINATIONS = 'VACCINATIONS';
export const VACCINATIONS_SUCCESS = 'VACCINATIONS_SUCCESS';
export const VACCINATIONS_ERROR = 'VACCINATIONS_ERROR';
export const VACCINATIONS__CLEAR = 'VACCINATIONS__CLEAR';

export const VACCINATIONS_GET = 'VACCINATIONS_GET';
export const VACCINATIONS_GET_SUCCESS = 'VACCINATIONS_GET_SUCCESS';
export const VACCINATIONS_GET_ERROR = 'VACCINATIONS_GET_ERROR';

export const VACCINATIONS_CREATE = 'VACCINATIONS_CREATE';
export const VACCINATIONS_CREATE_SUCCESS = 'VACCINATIONS_CREATE_SUCCESS';
export const VACCINATIONS_CREATE_ERROR = 'VACCINATIONS_CREATE_ERROR';

export const VACCINATIONS_UPDATE = 'VACCINATIONS_UPDATE';
export const VACCINATIONS_UPDATE_SUCCESS = 'VACCINATIONS_UPDATE_SUCCESS';
export const VACCINATIONS_UPDATE_ERROR = 'VACCINATIONS_UPDATE_ERROR';