export const HEIGHTANDWEIGHT = 'HEIGHTANDWEIGHT';
export const HEIGHTANDWEIGHT_SUCCESS = 'HEIGHTANDWEIGHT_SUCCESS';
export const HEIGHTANDWEIGHT_ERROR = 'HEIGHTANDWEIGHT_ERROR';
export const HEIGHTANDWEIGHT__CLEAR = 'HEIGHTANDWEIGHT__CLEAR';

export const HEIGHTANDWEIGHT_GET = 'HEIGHTANDWEIGHT_GET';
export const HEIGHTANDWEIGHT_GET_SUCCESS = 'HEIGHTANDWEIGHT_GET_SUCCESS';
export const HEIGHTANDWEIGHT_GET_ERROR = 'HEIGHTANDWEIGHT_GET_ERROR';

export const HEIGHTANDWEIGHT_CREATE = 'HEIGHTANDWEIGHT_CREATE';
export const HEIGHTANDWEIGHT_CREATE_SUCCESS = 'HEIGHTANDWEIGHT_CREATE_SUCCESS';
export const HEIGHTANDWEIGHT_CREATE_ERROR = 'HEIGHTANDWEIGHT_CREATE_ERROR';

export const HEIGHTANDWEIGHT_UPDATE = 'HEIGHTANDWEIGHT_UPDATE';
export const HEIGHTANDWEIGHT_UPDATE_SUCCESS = 'HEIGHTANDWEIGHT_UPDATE_SUCCESS';
export const HEIGHTANDWEIGHT_UPDATE_ERROR = 'HEIGHTANDWEIGHT_UPDATE_ERROR';