export const DRAWINGS = 'DRAWINGS';
export const DRAWINGS_SUCCESS = 'DRAWINGS_SUCCESS';
export const DRAWINGS_ERROR = 'DRAWINGS_ERROR';
export const DRAWINGS__CLEAR = 'DRAWINGS__CLEAR';

export const DRAWINGS_GET = 'DRAWINGS_GET';
export const DRAWINGS_GET_SUCCESS = 'DRAWINGS_GET_SUCCESS';
export const DRAWINGS_GET_ERROR = 'DRAWINGS_GET_ERROR';

export const DRAWINGS_CREATE = 'DRAWINGS_CREATE';
export const DRAWINGS_CREATE_SUCCESS = 'DRAWINGS_CREATE_SUCCESS';
export const DRAWINGS_CREATE_ERROR = 'DRAWINGS_CREATE_ERROR';

export const DRAWINGS_UPDATE = 'DRAWINGS_UPDATE';
export const DRAWINGS_UPDATE_SUCCESS = 'DRAWINGS_UPDATE_SUCCESS';
export const DRAWINGS_UPDATE_ERROR = 'DRAWINGS_UPDATE_ERROR';