export const DIAGNOSES = 'DIAGNOSES';
export const DIAGNOSES_SUCCESS = 'DIAGNOSES_SUCCESS';
export const DIAGNOSES_ERROR = 'DIAGNOSES_ERROR';
export const DIAGNOSES__CLEAR = 'DIAGNOSES__CLEAR';

export const DIAGNOSES_GET = 'DIAGNOSES_GET';
export const DIAGNOSES_GET_SUCCESS = 'DIAGNOSES_GET_SUCCESS';
export const DIAGNOSES_GET_ERROR = 'DIAGNOSES_GET_ERROR';

export const DIAGNOSES_CREATE = 'DIAGNOSES_CREATE';
export const DIAGNOSES_CREATE_SUCCESS = 'DIAGNOSES_CREATE_SUCCESS';
export const DIAGNOSES_CREATE_ERROR = 'DIAGNOSES_CREATE_ERROR';

export const DIAGNOSES_UPDATE = 'DIAGNOSES_UPDATE';
export const DIAGNOSES_UPDATE_SUCCESS = 'DIAGNOSES_UPDATE_SUCCESS';
export const DIAGNOSES_UPDATE_ERROR = 'DIAGNOSES_UPDATE_ERROR';