export const ORDERS = 'ORDERS';
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_ERROR = 'ORDERS_ERROR';
export const ORDERS__CLEAR = 'ORDERS__CLEAR';

export const ORDERS_GET = 'ORDERS_GET';
export const ORDERS_GET_SUCCESS = 'ORDERS_GET_SUCCESS';
export const ORDERS_GET_ERROR = 'ORDERS_GET_ERROR';

export const ORDERS_CREATE = 'ORDERS_CREATE';
export const ORDERS_CREATE_SUCCESS = 'ORDERS_CREATE_SUCCESS';
export const ORDERS_CREATE_ERROR = 'ORDERS_CREATE_ERROR';

export const ORDERS_SUGGESTION = 'ORDERS_SUGGESTION';
export const ORDERS_SUGGESTION_SUCCESS = 'ORDERS_SUGGESTION_SUCCESS';
export const ORDERS_SUGGESTION_ERROR = 'ORDERS_SUGGESTION_ERROR';