export const DOCUMENTS = 'DOCUMENTS';
export const DOCUMENTS_SUCCESS = 'DOCUMENTS_SUCCESS';
export const DOCUMENTS_ERROR = 'DOCUMENTS_ERROR';
export const DOCUMENTS__CLEAR = 'DOCUMENTS__CLEAR';

export const DOCUMENTS_GET = 'DOCUMENTS_GET';
export const DOCUMENTS_GET_SUCCESS = 'DOCUMENTS_GET_SUCCESS';
export const DOCUMENTS_GET_ERROR = 'DOCUMENTS_GET_ERROR';