export const REFERRALS = 'REFERRALS';
export const REFERRALS_SUCCESS = 'REFERRALS_SUCCESS';
export const REFERRALS_ERROR = 'REFERRALS_ERROR';
export const REFERRALS__CLEAR = 'REFERRALS__CLEAR';

export const REFERRALS_GET = 'REFERRALS_GET';
export const REFERRALS_GET_SUCCESS = 'REFERRALS_GET_SUCCESS';
export const REFERRALS_GET_ERROR = 'REFERRALS_GET_ERROR';

export const REFERRALS_CREATE = 'REFERRALS_CREATE';
export const REFERRALS_CREATE_SUCCESS = 'REFERRALS_CREATE_SUCCESS';
export const REFERRALS_CREATE_ERROR = 'REFERRALS_CREATE_ERROR';

export const REFERRALS_UPDATE = 'REFERRALS_UPDATE';
export const REFERRALS_UPDATE_SUCCESS = 'REFERRALS_UPDATE_SUCCESS';
export const REFERRALS_UPDATE_ERROR = 'REFERRALS_UPDATE_ERROR';