export const EVENTS = 'EVENTS';
export const EVENTS_SUCCESS = 'EVENTS_SUCCESS';
export const EVENTS_ERROR = 'EVENTS_ERROR';
export const EVENTS__CLEAR = 'EVENTS__CLEAR';

export const EVENTS_GET = 'EVENTS_GET';
export const EVENTS_GET_SUCCESS = 'EVENTS_GET_SUCCESS';
export const EVENTS_GET_ERROR = 'EVENTS_GET_ERROR';

export const EVENTS_CREATE = 'EVENTS_CREATE';
export const EVENTS_CREATE_SUCCESS = 'EVENTS_CREATE_SUCCESS';
export const EVENTS_CREATE_ERROR = 'EVENTS_CREATE_ERROR';

export const EVENTS_UPDATE = 'EVENTS_UPDATE';
export const EVENTS_UPDATE_SUCCESS = 'EVENTS_UPDATE_SUCCESS';
export const EVENTS_UPDATE_ERROR = 'EVENTS_UPDATE_ERROR';