export const EOLCAREPLANS = 'EOLCAREPLANS';
export const EOLCAREPLANS_SUCCESS = 'EOLCAREPLANS_SUCCESS';
export const EOLCAREPLANS_ERROR = 'EOLCAREPLANS_ERROR';
export const EOLCAREPLANS__CLEAR = 'EOLCAREPLANS__CLEAR';

export const EOLCAREPLANS_GET = 'EOLCAREPLANS_GET';
export const EOLCAREPLANS_GET_SUCCESS = 'EOLCAREPLANS_GET_SUCCESS';
export const EOLCAREPLANS_GET_ERROR = 'EOLCAREPLANS_GET_ERROR';

export const EOLCAREPLANS_CREATE = 'EOLCAREPLANS_CREATE';
export const EOLCAREPLANS_CREATE_SUCCESS = 'EOLCAREPLANS_CREATE_SUCCESS';
export const EOLCAREPLANS_CREATE_ERROR = 'EOLCAREPLANS_CREATE_ERROR';

export const EOLCAREPLANS_UPDATE = 'EOLCAREPLANS_UPDATE';
export const EOLCAREPLANS_UPDATE_SUCCESS = 'EOLCAREPLANS_UPDATE_SUCCESS';
export const EOLCAREPLANS_UPDATE_ERROR = 'EOLCAREPLANS_UPDATE_ERROR';