export const VITALS = 'VITALS';
export const VITALS_SUCCESS = 'VITALS_SUCCESS';
export const VITALS_ERROR = 'VITALS_ERROR';
export const VITALS__CLEAR = 'VITALS__CLEAR';

export const VITALS_GET = 'VITALS_GET';
export const VITALS_GET_SUCCESS = 'VITALS_GET_SUCCESS';
export const VITALS_GET_ERROR = 'VITALS_GET_ERROR';

export const VITALS_CREATE = 'VITALS_CREATE';
export const VITALS_CREATE_SUCCESS = 'VITALS_CREATE_SUCCESS';
export const VITALS_CREATE_ERROR = 'VITALS_CREATE_ERROR';

export const VITALS_UPDATE = 'VITALS_UPDATE';
export const VITALS_UPDATE_SUCCESS = 'VITALS_UPDATE_SUCCESS';
export const VITALS_UPDATE_ERROR = 'VITALS_UPDATE_ERROR';