export const PROCEDURES = 'PROCEDURES';
export const PROCEDURES_SUCCESS = 'PROCEDURES_SUCCESS';
export const PROCEDURES_ERROR = 'PROCEDURES_ERROR';
export const PROCEDURES__CLEAR = 'PROCEDURES__CLEAR';

export const PROCEDURES_GET = 'PROCEDURES_GET';
export const PROCEDURES_GET_SUCCESS = 'PROCEDURES_GET_SUCCESS';
export const PROCEDURES_GET_ERROR = 'PROCEDURES_GET_ERROR';

export const PROCEDURES_CREATE = 'PROCEDURES_CREATE';
export const PROCEDURES_CREATE_SUCCESS = 'PROCEDURES_CREATE_SUCCESS';
export const PROCEDURES_CREATE_ERROR = 'PROCEDURES_CREATE_ERROR';

export const PROCEDURES_UPDATE = 'PROCEDURES_UPDATE';
export const PROCEDURES_UPDATE_SUCCESS = 'PROCEDURES_UPDATE_SUCCESS';
export const PROCEDURES_UPDATE_ERROR = 'PROCEDURES_UPDATE_ERROR';