export const PERSONALNOTES = 'PERSONALNOTES';
export const PERSONALNOTES_SUCCESS = 'PERSONALNOTES_SUCCESS';
export const PERSONALNOTES_ERROR = 'PERSONALNOTES_ERROR';
export const PERSONALNOTES__CLEAR = 'PERSONALNOTES__CLEAR';

export const PERSONALNOTES_GET = 'PERSONALNOTES_GET';
export const PERSONALNOTES_GET_SUCCESS = 'PERSONALNOTES_GET_SUCCESS';
export const PERSONALNOTES_GET_ERROR = 'PERSONALNOTES_GET_ERROR';

export const PERSONALNOTES_CREATE = 'PERSONALNOTES_CREATE';
export const PERSONALNOTES_CREATE_SUCCESS = 'PERSONALNOTES_CREATE_SUCCESS';
export const PERSONALNOTES_CREATE_ERROR = 'PERSONALNOTES_CREATE_ERROR';

export const PERSONALNOTES_UPDATE = 'PERSONALNOTES_UPDATE';
export const PERSONALNOTES_UPDATE_SUCCESS = 'PERSONALNOTES_UPDATE_SUCCESS';
export const PERSONALNOTES_UPDATE_ERROR = 'PERSONALNOTES_UPDATE_ERROR';