export const CONTACTS = 'CONTACTS';
export const CONTACTS_SUCCESS = 'CONTACTS_SUCCESS';
export const CONTACTS_ERROR = 'CONTACTS_ERROR';
export const CONTACTS__CLEAR = 'CONTACTS__CLEAR';

export const CONTACTS_GET = 'CONTACTS_GET';
export const CONTACTS_GET_SUCCESS = 'CONTACTS_GET_SUCCESS';
export const CONTACTS_GET_ERROR = 'CONTACTS_GET_ERROR';

export const CONTACTS_CREATE = 'CONTACTS_CREATE';
export const CONTACTS_CREATE_SUCCESS = 'CONTACTS_CREATE_SUCCESS';
export const CONTACTS_CREATE_ERROR = 'CONTACTS_CREATE_ERROR';

export const CONTACTS_UPDATE = 'CONTACTS_UPDATE';
export const CONTACTS_UPDATE_SUCCESS = 'CONTACTS_UPDATE_SUCCESS';
export const CONTACTS_UPDATE_ERROR = 'CONTACTS_UPDATE_ERROR';